# Utility parameters for the microsimulation (python) part.
# These can also be passed as command line arguments
microsim:
  scenario: "TestScenario" # name for scenario directory
  iterations: 10 # Number of model iterations. 0 means just run the initialisation.
  data-dir: devon_data # Root directory to load data from
  output: true # Whether to generate output or not
  output-every-iteration: false # Can optionally write output at every iteration, not just at the end
  debug: false # Whether to run some more expensive checks
  repetitions: 1 # How many times to run the model
  lockdown-file: "google_mobility_lockdown_daily.csv" # Read lockdown mobility data from a file? (Empty string means no lockdown)

# Parameters that are used to calibrate the model.
# These can only be passed using the parameters file
microsim_calibration:
  # These multiply the amount of hazard that individuals pass on to shops etc:
  hazard_individual_multipliers:
    presymptomatic: 1.0
    asymptomatic: 1.0
    symptomatic: 1.0
  # Different locations can also have their own multipliers (e.g. to make it easier to pass the disease on to shops than schools)
  hazard_location_multipliers:
    Retail: 1.0
    PrimarySchool: 1.0
    SecondarySchool: 1.0
    Home: 1.0
    Work: 1.0
  # This multiplies the risk received as individuals visit shops etc.
  risk_multiplier: 1.0


disease: # This is where the parameter for the disease model (the R part) can go (same format the 'microsim_calibration' above)
  current_risk_beta: 0.008
  risk_cap: 5
  seed_days: 5
  exposed_dist: "weibull"
  exposed_mean: 2.56
  exposed_sd: 0.72
  presymp_dist: "weibull"
  presymp_mean: 2.3
  presymp_sd: 0.35
  infection_dist: "normal"
  infection_mean: 16
  infection_sd: 3
  asymp_rate: 0.35
  output_switch: TRUE
  rank_assign: FALSE
  local_outbreak_timestep: 2
  local_outbreak: TRUE
  msoa_infect: "E02004161"
  number_people_local: 100
  local_prob_increase: 1.0
  
